services:
  - type: web
    name: go-crud-app
    env: go-crud-app
    runtime: image
    git:
      depth: false
    image:
      name: golang:1.21-bullseye
      preBuildCommands:
        - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
        - apt-get update && apt-get install -y nodejs
        - npm install -g prisma dotenv-cli
        - npx prisma generate
      buildCommand: |
        go mod tidy
      startCommand: dotenv -e .env -- go run main.go
    envVars:
      - key: PORT
        value: 10000
      - key: CORS_ORIGINS
        value: https://go-server-todo-frontend.vercel.app/
databases:
  - name: go-crud-app
    plan: free
