services:
  - type: web
    name: github.com/Bhuwan-Darai/goCrud
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 8080
