services:
  - type: web
    name: go-server-todo
    env: docker
    dockerfilePath: ./Dockerfile.render
    region: oregon
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 8000
      - key: ENV
        value: production
