package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"context"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/Bhuwan-Darai/goCrud/graph/model"
	db "github.com/Bhuwan-Darai/goCrud/prisma/db/prisma-client"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, name string, email string) (*model.User, error) {
	user, err := r.DB.User.CreateOne(
		db.User.Name.Set(name),
		db.User.Email.Set(email),
		db.User.CreatedAt.Set(time.Now()),
	).Exec(ctx)
	if err != nil {
		if strings.Contains(err.Error(), "Unique constraint failed") {
			return nil, fmt.Errorf("email already exists")
		}
		return nil, fmt.Errorf("failed to create user: %v", err)
	}
	return &model.User{
		ID:        strconv.Itoa(user.ID),
		Name:      user.Name,
		Email:     user.Email,
		CreatedAt: user.CreatedAt.String(),
	}, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, name *string, email *string) (*model.User, error) {
	// Convert string ID to int
	userID, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %v", err)
	}

	// Build update parameters
	updateParams := []db.UserSetParam{}

	if name != nil {
		updateParams = append(updateParams, db.User.Name.Set(*name))
	}

	if email != nil {
		updateParams = append(updateParams, db.User.Email.Set(*email))
	}

	// If no fields to update, return error
	if len(updateParams) == 0 {
		return nil, fmt.Errorf("no fields provided for update")
	}

	// Update the user
	user, err := r.DB.User.FindUnique(
		db.User.ID.Equals(userID),
	).Update(updateParams...).Exec(ctx)

	if err != nil {
		if strings.Contains(err.Error(), "Record to update not found") {
			return nil, fmt.Errorf("user not found")
		}
		if strings.Contains(err.Error(), "Unique constraint failed") {
			return nil, fmt.Errorf("email already exists")
		}
		return nil, fmt.Errorf("failed to update user: %v", err)
	}

	return &model.User{
		ID:        strconv.Itoa(user.ID),
		Name:      user.Name,
		Email:     user.Email,
		CreatedAt: user.CreatedAt.String(),
	}, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (*model.User, error) {
	// Convert string ID to int
	userID, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %v", err)
	}

	// First, get the user to return it after deletion
	user, err := r.DB.User.FindUnique(
		db.User.ID.Equals(userID),
	).Exec(ctx)

	if err != nil {
		if strings.Contains(err.Error(), "No User found") {
			return nil, fmt.Errorf("user not found")
		}
		return nil, fmt.Errorf("failed to find user: %v", err)
	}

	// Delete the user
	_, err = r.DB.User.FindUnique(
		db.User.ID.Equals(userID),
	).Delete().Exec(ctx)

	if err != nil {
		return nil, fmt.Errorf("failed to delete user: %v", err)
	}

	return &model.User{
		ID:        strconv.Itoa(user.ID),
		Name:      user.Name,
		Email:     user.Email,
		CreatedAt: user.CreatedAt.String(),
	}, nil
}

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.TaskInput) (*model.Response, error) {
	task, err := r.DB.Task.CreateOne(
		db.Task.Title.Set(input.Title),
	).Exec(ctx)

	if err != nil {
		return nil, fmt.Errorf("failed to create task: %v", err)
	}

	return &model.Response{
		Data: map[string]interface{}{
			"message": "Task created successfully",
			"success": true,
			"task":    task,
		},
	}, nil
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, taskID string, input model.TaskInput) (*model.Response, error) {
	panic(fmt.Errorf("not implemented: UpdateTask - updateTask"))
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, taskID string) (*model.Response, error) {
	// Try to find the task first
	taskQuery := r.DB.Task.FindUnique(
		db.Task.TaskID.Equals(taskID),
	)

	task, err := taskQuery.Exec(ctx)
	if err != nil {
		if strings.Contains(err.Error(), "No Task found") {
			return &model.Response{
				Success: false,
				Message: "Task not found",
			}, nil
		}
		return &model.Response{
			Success: false,
			Message: fmt.Sprintf("Failed to query task: %v", err),
		}, nil
	}

	// Delete the task
	_, err = taskQuery.Delete().Exec(ctx)
	if err != nil {
		return &model.Response{
			Success: false,
			Message: fmt.Sprintf("Failed to delete task: %v", err),
		}, nil
	}

	return &model.Response{
		Success: true,
		Message: "Task deleted successfully",
		Data: map[string]interface{}{
			"taskId": task.TaskID,
			"title":  task.Title,
		},
	}, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	users, err := r.DB.User.FindMany().Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch users: %v", err)
	}

	var result []*model.User
	for _, user := range users {
		result = append(result, &model.User{
			ID:        strconv.Itoa(user.ID),
			Name:      user.Name,
			Email:     user.Email,
			CreatedAt: user.CreatedAt.String(),
		})
	}

	return result, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	// Convert string ID to int
	userID, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %v", err)
	}

	user, err := r.DB.User.FindUnique(
		db.User.ID.Equals(userID),
	).Exec(ctx)

	if err != nil {
		if strings.Contains(err.Error(), "No User found") {
			return nil, fmt.Errorf("user not found")
		}
		return nil, fmt.Errorf("failed to fetch user: %v", err)
	}

	return &model.User{
		ID:        strconv.Itoa(user.ID),
		Name:      user.Name,
		Email:     user.Email,
		CreatedAt: user.CreatedAt.String(),
	}, nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) (*model.ResponseWithData, error) {
	tasks, err := r.DB.Task.FindMany().OrderBy(db.Task.CreatedAt.Order(db.DESC)).Exec(ctx)

	fmt.Println("tasks", tasks)

	if err != nil {
		return &model.ResponseWithData{
			Success: false,
			Message: "Failed to fetch tasks",
		}, err
	}

	var result []*model.Task

	for _, task := range tasks {
		result = append(result, &model.Task{
			ID:     int32(task.ID),
			TaskID: task.TaskID,
			Title:  task.Title,
		})
	}

	response := &model.ResponseWithData{
		Success: true,
		Message: "Tasks fetched successfully",
		Data:    result,
	}

	// Log the response before returning
	fmt.Println("response", response)

	return response, nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, taskID string) (*model.Task, error) {
	panic(fmt.Errorf("not implemented: Task - task"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
